// apps/website/src/components/navbar.tsx
'use client';

import { ExternalLink, Menu, X } from 'lucide-react';

import { useState } from 'react';

import Image from 'next/image';
import Link from 'next/link';
import { usePathname } from 'next/navigation';

import { siteConfig } from '@/config/site';
import { cn } from '@/lib/utils';

type NavLink = {
  href: string;
  label: string;
  external?: boolean;
  icon?: React.ComponentType<{ className: string }>;
};

const LINKS = {
  nav: [
    { href: '/team', label: 'Team' },
    { href: 'https://docs.bxteam.org', label: 'Docs', external: true },
    { href: 'https://status.bxteam.org', label: 'Status', external: true },
    { href: 'https://repo.bxteam.org', label: 'Maven Repo', external: true },
  ],
  social: [
    {
      href: siteConfig.links.github,
      label: 'GitHub',
      external: true,
      icon: ({ className }: { className: string }) => (
        <svg viewBox='0 0 24 24' className={className} fill='currentColor' aria-hidden='true' role='img'>
          <title>GitHub</title>
          <path d='M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z' />
        </svg>
      ),
    },
    {
      href: siteConfig.links.discord,
      label: 'Discord',
      external: true,
      icon: ({ className }: { className: string }) => (
        <svg viewBox='0 0 24 24' className={className} fill='currentColor' aria-hidden='true' role='img'>
          <title>Discord</title>
          <path d='M20.317 4.492c-1.53-.69-3.17-1.2-4.885-1.49a.075.075 0 0 0-.079.036c-.21.369-.444.85-.608 1.23a18.566 18.566 0 0 0-5.487 0 12.36 12.36 0 0 0-.617-1.23A.077.077 0 0 0 8.562 3c-1.714.29-3.354.8-4.885 1.491a.07.07 0 0 0-.032.027C.533 9.093-.32 13.555.099 17.961a.08.08 0 0 0 .031.055 20.03 20.03 0 0 0 5.993 2.98.078.078 0 0 0 .084-.026c.462-.62.874-1.275 1.226-1.963.021-.04.001-.088-.041-.104a13.201 13.201 0 0 1-1.872-.878.075.075 0 0 1-.008-.125c.126-.093.252-.19.372-.287a.075.075 0 0 1 .078-.01c3.927 1.764 8.18 1.764 12.061 0a.075.075 0 0 1 .079.009c.12.098.245.195.372.288a.075.075 0 0 1-.006.125c-.598.344-1.22.635-1.873.877a.075.075 0 0 0-.041.105c.36.687.772 1.341 1.225 1.962a.077.077 0 0 0 .084.028 19.963 19.963 0 0 0 6.002-2.981.076.076 0 0 0 .032-.054c.5-5.094-.838-9.52-3.549-13.442a.06.06 0 0 0-.031-.028zM8.02 15.278c-1.182 0-2.157-1.069-2.157-2.38 0-1.312.956-2.38 2.157-2.38 1.21 0 2.176 1.077 2.157 2.38 0 1.312-.956 2.38-2.157 2.38zm7.975 0c-1.183 0-2.157-1.069-2.157-2.38 0-1.312.955-2.38 2.157-2.38 1.21 0 2.176 1.077 2.157 2.38 0 1.312-.946 2.38-2.157 2.38z' />
        </svg>
      ),
    },
  ],
} as const;

function NavbarLink({ href, label, external, icon: Icon, className }: NavLink & { className?: string }) {
  const pathname = usePathname();
  const isActive = pathname === href;
  const Comp = external ? 'a' : Link;

  return (
    <Comp
      href={href}
      className={cn(
        'flex items-center gap-1.5 text-sm transition-colors duration-200',
        isActive ? 'text-white' : 'text-neutral-300 hover:text-neutral-100',
        className,
      )}
      aria-label={label}
      aria-current={isActive ? 'page' : undefined}
      {...(external && {
        target: '_blank',
        rel: 'noopener noreferrer',
        'aria-label': `${label} (opens in new tab)`,
      })}
    >
      {Icon ? (
        <Icon className='h-5 w-5' />
      ) : (
        <>
          {label}
          {external && <ExternalLink className='h-3.5 w-3.5' aria-hidden='true' />}
        </>
      )}
    </Comp>
  );
}

export function Navbar() {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <nav
      className='supports-[backdrop-filter]:bg-background/90 fixed left-0 right-0 top-0 z-50 border-b border-neutral-800 text-white backdrop-blur-sm'
      role='navigation'
    >
      <div className='mx-auto max-w-7xl px-4 sm:px-6 lg:px-8'>
        <div className='h-15 flex items-center justify-between'>
          <div className='flex items-center space-x-6'>
            <Link href='/' className='flex items-center space-x-2 hover:opacity-90' aria-label='BX Team'>
              <Image src='/logo.png' alt='' width={28} height={28} className='rounded-md' priority />
              <span className='text-sm font-semibold'>BX Team</span>
            </Link>
            <div className='hidden md:flex md:space-x-4' role='menubar'>
              {LINKS.nav.map((link) => (
                <NavbarLink key={link.href} {...link} />
              ))}
            </div>
          </div>

          <div className='hidden md:flex md:items-center md:space-x-5' role='menubar' aria-label='Social links'>
            {LINKS.social.map((link) => (
              <NavbarLink key={link.href} {...link} />
            ))}
          </div>

          <button
            onClick={() => setIsOpen((p) => !p)}
            className='inline-flex items-center justify-center rounded-md p-2.5 text-neutral-300 transition-colors hover:bg-neutral-800 md:hidden'
            aria-expanded={isOpen}
            aria-controls='mobile-menu'
            aria-label={`${isOpen ? 'Close' : 'Open'} menu`}
          >
            {isOpen ? <X className='h-6 w-6' /> : <Menu className='h-6 w-6' />}
          </button>
        </div>
      </div>

      {isOpen && (
        <div
          id='mobile-menu'
          className='bg-background top-15 absolute left-0 right-0 border-b border-t border-neutral-800 pt-5 md:hidden'
          role='menu'
          aria-label='Mobile navigation'
        >
          <div className='space-y-1 px-2 pb-3'>
            {LINKS.nav.map((link) => (
              <NavbarLink
                key={link.href}
                {...link}
                className='flex items-center rounded-md px-3 py-2 transition-colors hover:bg-neutral-800'
              />
            ))}
            <div className='-mx-4 pt-3 sm:-mx-6 lg:-mx-8'>
              <div className='border-t border-neutral-800'>
                <div className='flex gap-2 px-6 pt-3' role='menu' aria-label='Mobile social links'>
                  {LINKS.social.map((link) => (
                    <NavbarLink
                      key={link.href}
                      {...link}
                      className='rounded-md p-1.5 transition-colors hover:bg-neutral-800'
                    />
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>
      )}
    </nav>
  );
}

// app/components/ui/Navbar.vue
<script setup lang="ts">
import { Menu, X, Github } from 'lucide-vue-next';
import { siteConfig } from '@/config/site';

const mobileMenuOpen = ref(false);

const navLinks = [
  { label: 'Documentation', to: '/docs', external: false },
  { label: 'Team', to: '/team', external: false },
  { label: 'Status', to: 'https://status.bxteam.org', external: true },
];
</script>

<template>
  <header class="sticky top-0 z-50 border-b border-neutral-800/80 bg-background/80 backdrop-blur-xl">
    <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
      <div class="flex h-14 items-center justify-between gap-4">
        <!-- Logo and Navigation -->
        <div class="flex items-center gap-6">
          <NuxtLink
            to="/"
            class="inline-flex items-center gap-2 rounded-lg transition-opacity hover:opacity-90 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white/20 shrink-0"
          >
            <NuxtImg src="/logo.png" alt="BX Team" width="28" height="28" class="rounded-xl" />
            <span class="font-semibold text-sm">BX Team</span>
          </NuxtLink>

          <!-- Desktop navigation -->
          <nav class="hidden md:flex items-center gap-1">
            <template v-for="link in navLinks" :key="link.to">
              <a
                v-if="link.external"
                :href="link.to"
                target="_blank"
                rel="noopener noreferrer"
                class="px-3 py-2 text-sm font-medium text-[#7E7E7E] hover:text-foreground transition-colors rounded-md focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/50"
              >{{ link.label }}</a>
              <NuxtLink
                v-else
                :to="link.to"
                class="px-3 py-2 text-sm font-medium text-[#7E7E7E] hover:text-foreground transition-colors rounded-md focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/50"
              >{{ link.label }}</NuxtLink>
            </template>
          </nav>
        </div>

        <!-- Social links + mobile toggle -->
        <div class="flex items-center gap-2">
          <a
            :href="siteConfig.links.github"
            target="_blank"
            rel="noopener noreferrer"
            aria-label="GitHub"
            class="rounded-md p-2 text-neutral-400 transition-colors hover:text-neutral-100"
          >
            <Github class="size-4.5" />
          </a>
          <a
            :href="siteConfig.links.discord"
            target="_blank"
            rel="noopener noreferrer"
            aria-label="Discord"
            class="rounded-md p-2 text-neutral-400 transition-colors hover:text-neutral-100"
          >
            <!-- Discord icon (SVG) -->
            <svg role="img" viewBox="0 0 24 24" class="size-4.5 fill-current" xmlns="http://www.w3.org/2000/svg">
              <path d="M20.317 4.37a19.791 19.791 0 0 0-4.885-1.515.074.074 0 0 0-.079.037c-.21.375-.444.864-.608 1.25a18.27 18.27 0 0 0-5.487 0 12.64 12.64 0 0 0-.617-1.25.077.077 0 0 0-.079-.037A19.736 19.736 0 0 0 3.677 4.37a.07.07 0 0 0-.032.027C.533 9.046-.32 13.58.099 18.057c.002.022.015.043.03.056A19.9 19.9 0 0 0 6.1 21.022a.077.077 0 0 0 .084-.028 14.09 14.09 0 0 0 1.226-1.994.076.076 0 0 0-.041-.106 13.107 13.107 0 0 1-1.872-.892.077.077 0 0 1-.008-.128 10.2 10.2 0 0 0 .372-.292.074.074 0 0 1 .077-.01c3.928 1.793 8.18 1.793 12.062 0a.074.074 0 0 1 .078.01c.12.098.246.198.373.292a.077.077 0 0 1-.006.127 12.299 12.299 0 0 1-1.873.892.077.077 0 0 0-.041.107c.36.698.772 1.362 1.225 1.993a.076.076 0 0 0 .084.028 19.839 19.839 0 0 0 6.002-3.03.077.077 0 0 0 .032-.054c.5-5.177-.838-9.674-3.549-13.66a.061.061 0 0 0-.031-.03zM8.02 15.33c-1.183 0-2.157-1.085-2.157-2.419 0-1.333.956-2.419 2.157-2.419 1.21 0 2.176 1.096 2.157 2.42 0 1.333-.956 2.418-2.157 2.418zm7.975 0c-1.183 0-2.157-1.085-2.157-2.419 0-1.333.955-2.419 2.157-2.419 1.21 0 2.176 1.096 2.157 2.42 0 1.333-.946 2.418-2.157 2.418z" />
            </svg>
          </a>

          <!-- Mobile hamburger -->
          <button
            class="md:hidden rounded-md p-2 text-neutral-400 transition-colors hover:text-neutral-100"
            :aria-label="mobileMenuOpen ? 'Close menu' : 'Open menu'"
            @click="mobileMenuOpen = !mobileMenuOpen"
          >
            <X v-if="mobileMenuOpen" class="size-5" />
            <Menu v-else class="size-5" />
          </button>
        </div>
      </div>
    </div>

    <!-- Mobile menu -->
    <div v-show="mobileMenuOpen" class="border-t border-neutral-800/80 md:hidden">
      <nav class="mx-auto max-w-7xl space-y-1 px-4 py-3 sm:px-6">
        <template v-for="link in navLinks" :key="link.to">
          <a
            v-if="link.external"
            :href="link.to"
            target="_blank"
            rel="noopener noreferrer"
            class="block rounded-md px-3 py-2 text-sm text-[#7E7E7E] hover:text-foreground transition-colors hover:bg-accent"
            @click="mobileMenuOpen = false"
          >{{ link.label }}</a>
          <NuxtLink
            v-else
            :to="link.to"
            class="block rounded-md px-3 py-2 text-sm text-[#7E7E7E] hover:text-foreground transition-colors hover:bg-accent"
            @click="mobileMenuOpen = false"
          >{{ link.label }}</NuxtLink>
        </template>
      </nav>
    </div>
  </header>
</template>
